# Generated by Django 6.0.8 on 2026-10-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_alter_product_discount_price_alter_product_price"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["is_active", "is_featured"], name="products_pr_is_acti_2fee29_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["is_active", "-created_at"], name="products_pr_is_acti_645007_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["category", "is_active"], name="products_pr_categor_50f5f1_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["brand", "is_active"], name="products_pr_brand_i_8f789e_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["store", "is_active"], name="products_pr_store_i_719494_idx"),
        ),
    ]
